repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # - id: no-commit-to-branch
      #   args: [--branch, main]
      #   stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
  - repo: local
    hooks:
      # Rust hooks
      - id: clippy
        name: cargo clippy
        description: This hook runs cargo clippy on the project and fixes any issues.
        entry: cargo clippy --fix --allow-dirty --allow-staged --all-targets --quiet -- -D warnings
        language: system
        types: [rust]
        stages: [pre-commit]
        pass_filenames: false
      - id: fmt
        name: cargo fmt
        description: This hook runs cargo fmt on the project
        entry: cargo +nightly fmt --all
        language: system
        types: [rust]
        stages: [pre-commit]
        pass_filenames: false

      # Justfile hooks
      - id: just-fmt
        name: just fmt
        entry: just --unstable --fmt
        language: system
        files: ^justfile$
        stages: [pre-commit]
        pass_filenames: false
