application:
  port: 8080
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "audioIdentifier"
  require_ssl: true
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_ms: 10000
